# Anna KaRNNa

In this notebook, we'll build a character-wise RNN trained on Anna Karenina, one of my all-time favorite books. It'll be able to generate new text based on the text from the book.

This network is based off of Andrej Karpathy's [post on RNNs](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) and [implementation in Torch](https://github.com/karpathy/char-rnn). Also, some information [here at r2rt](http://r2rt.com/recurrent-neural-networks-in-tensorflow-ii.html) and from [Sherjil Ozair](https://github.com/sherjilozair/char-rnn-tensorflow) on GitHub. Below is the general architecture of the character-wise RNN.

<img src="assets/charseq.jpeg" width="500">

In [1]:
import time
from collections import namedtuple

import numpy as np
import tensorflow as tf

First we'll load the text file and convert it into integers for our network to use. Here I'm creating a couple dictionaries to convert the characters to and from integers. Encoding the characters as integers makes it easier to use as input in the network.

In [2]:
with open('anna.txt', 'r') as f:
    text=f.read()
vocab = sorted(set(text))
vocab_to_int = {c: i for i, c in enumerate(vocab)}
int_to_vocab = dict(enumerate(vocab))
encoded = np.array([vocab_to_int[c] for c in text], dtype=np.int32)

Let's check out the first 100 characters, make sure everything is peachy. According to the [American Book Review](http://americanbookreview.org/100bestlines.asp), this is the 6th best first line of a book ever.

In [3]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

And we can see the characters encoded as integers.

In [4]:
encoded[:100]

array([31, 64, 57, 72, 76, 61, 74,  1, 16,  0,  0,  0, 36, 57, 72, 72, 81,
        1, 62, 57, 69, 65, 68, 65, 61, 75,  1, 57, 74, 61,  1, 57, 68, 68,
        1, 57, 68, 65, 67, 61, 26,  1, 61, 78, 61, 74, 81,  1, 77, 70, 64,
       57, 72, 72, 81,  1, 62, 57, 69, 65, 68, 81,  1, 65, 75,  1, 77, 70,
       64, 57, 72, 72, 81,  1, 65, 70,  1, 65, 76, 75,  1, 71, 79, 70,  0,
       79, 57, 81, 13,  0,  0, 33, 78, 61, 74, 81, 76, 64, 65, 70], dtype=int32)

Since the network is working with individual characters, it's similar to a classification problem in which we are trying to predict the next character from the previous text.  Here's how many 'classes' our network has to pick from.

In [5]:
len(vocab)

83

## Making training mini-batches

Here is where we'll make our mini-batches for training. Remember that we want our batches to be multiple sequences of some desired number of sequence steps. Considering a simple example, our batches would look like this:

<img src="assets/sequence_batching@1x.png" width=500px>


<br>
We have our text encoded as integers as one long array in `encoded`. Let's create a function that will give us an iterator for our batches. I like using [generator functions](https://jeffknupp.com/blog/2013/04/07/improve-your-python-yield-and-generators-explained/) to do this. Then we can pass `encoded` into this function and get our batch generator.

The first thing we need to do is discard some of the text so we only have completely full batches. Each batch contains $N \times M$ characters, where $N$ is the batch size (the number of sequences) and $M$ is the number of steps. Then, to get the number of batches we can make from some array `arr`, you divide the length of `arr` by the batch size. Once you know the number of batches and the batch size, you can get the total number of characters to keep.

After that, we need to split `arr` into $N$ sequences. You can do this using `arr.reshape(size)` where `size` is a tuple containing the dimensions sizes of the reshaped array. We know we want $N$ sequences (`n_seqs` below), let's make that the size of the first dimension. For the second dimension, you can use `-1` as a placeholder in the size, it'll fill up the array with the appropriate data for you. After this, you should have an array that is $N \times (M * K)$ where $K$ is the number of batches.

Now that we have this array, we can iterate through it to get our batches. The idea is each batch is a $N \times M$ window on the array. For each subsequent batch, the window moves over by `n_steps`. We also want to create both the input and target arrays. Remember that the targets are the inputs shifted over one character. You'll usually see the first input character used as the last target character, so something like this:
```python
y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
```
where `x` is the input batch and `y` is the target batch.

The way I like to do this window is use `range` to take steps of size `n_steps` from $0$ to `arr.shape[1]`, the total number of steps in each sequence. That way, the integers you get from `range` always point to the start of a batch, and each window is `n_steps` wide.

> **Exercise:** Write the code for creating batches in the function below. The exercises in this notebook _will not be easy_. I've provided a notebook with solutions alongside this notebook. If you get stuck, checkout the solutions. The most important thing is that you don't copy and paste the code into here, **type out the solution code yourself.**

In [6]:
def get_batches(arr, n_seqs, n_steps):
    '''Create a generator that returns batches of size
       n_seqs x n_steps from arr.
       
       Arguments
       ---------
       arr: Array you want to make batches from
       n_seqs: Batch size, the number of sequences per batch
       n_steps: Number of sequence steps per batch
    '''
    # Get the number of characters per batch and number of batches we can make
    characters_per_batch = n_seqs * n_steps
    n_batches = arr.shape[0] // characters_per_batch
    
    # Keep only enough characters to make full batches
    arr = arr[:n_batches * characters_per_batch]
    
    # Reshape into n_seqs rows
    arr = arr.reshape((n_seqs,-1))
    
    for n in range(0, arr.shape[1], n_steps):
        # The features
        x = arr[:,n:n+n_steps]
        # The targets, shifted by one
        y = np.zeros_like(x)
        y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
        yield x, y

Now I'll make my data sets and we can check out what's going on here. Here I'm going to use a batch size of 10 and 50 sequence steps.

In [7]:
batches = get_batches(encoded, 10, 50)
x, y = next(batches)

In [8]:
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[31 64 57 72 76 61 74  1 16  0]
 [ 1 57 69  1 70 71 76  1 63 71]
 [78 65 70 13  0  0  3 53 61 75]
 [70  1 60 77 74 65 70 63  1 64]
 [ 1 65 76  1 65 75 11  1 75 65]
 [ 1 37 76  1 79 57 75  0 71 70]
 [64 61 70  1 59 71 69 61  1 62]
 [26  1 58 77 76  1 70 71 79  1]
 [76  1 65 75 70  7 76 13  1 48]
 [ 1 75 57 65 60  1 76 71  1 64]]

y
 [[64 57 72 76 61 74  1 16  0  0]
 [57 69  1 70 71 76  1 63 71 65]
 [65 70 13  0  0  3 53 61 75 11]
 [ 1 60 77 74 65 70 63  1 64 65]
 [65 76  1 65 75 11  1 75 65 74]
 [37 76  1 79 57 75  0 71 70 68]
 [61 70  1 59 71 69 61  1 62 71]
 [ 1 58 77 76  1 70 71 79  1 75]
 [ 1 65 75 70  7 76 13  1 48 64]
 [75 57 65 60  1 76 71  1 64 61]]


If you implemented `get_batches` correctly, the above output should look something like 
```
x
 [[55 63 69 22  6 76 45  5 16 35]
 [ 5 69  1  5 12 52  6  5 56 52]
 [48 29 12 61 35 35  8 64 76 78]
 [12  5 24 39 45 29 12 56  5 63]
 [ 5 29  6  5 29 78 28  5 78 29]
 [ 5 13  6  5 36 69 78 35 52 12]
 [63 76 12  5 18 52  1 76  5 58]
 [34  5 73 39  6  5 12 52 36  5]
 [ 6  5 29 78 12 79  6 61  5 59]
 [ 5 78 69 29 24  5  6 52  5 63]]

y
 [[63 69 22  6 76 45  5 16 35 35]
 [69  1  5 12 52  6  5 56 52 29]
 [29 12 61 35 35  8 64 76 78 28]
 [ 5 24 39 45 29 12 56  5 63 29]
 [29  6  5 29 78 28  5 78 29 45]
 [13  6  5 36 69 78 35 52 12 43]
 [76 12  5 18 52  1 76  5 58 52]
 [ 5 73 39  6  5 12 52 36  5 78]
 [ 5 29 78 12 79  6 61  5 59 63]
 [78 69 29 24  5  6 52  5 63 76]]
 ```
 although the exact numbers will be different. Check to make sure the data is shifted over one step for `y`.

## Building the model

Below is where you'll build the network. We'll break it up into parts so it's easier to reason about each bit. Then we can connect them up into the whole network.

<img src="assets/charRNN.png" width=500px>


### Inputs

First off we'll create our input placeholders. As usual we need placeholders for the training data and the targets. We'll also create a placeholder for dropout layers called `keep_prob`. This will be a scalar, that is a 0-D tensor. To make a scalar, you create a placeholder without giving it a size.

> **Exercise:** Create the input placeholders in the function below.

In [9]:
def build_inputs(batch_size, num_steps):
    ''' Define placeholders for inputs, targets, and dropout 
    
        Arguments
        ---------
        batch_size: Batch size, number of sequences per batch
        num_steps: Number of sequence steps in a batch
        
    '''
    # Declare placeholders we'll feed into the graph
    inputs = tf.placeholder(tf.int32, [batch_size, num_steps], name='inputs')
    targets = tf.placeholder(tf.int32, [batch_size, num_steps], name='targets')
    
    # Keep probability placeholder for drop out layers
    keep_prob = tf.placeholder(tf.float32, name='keep_prob')
    
    return inputs, targets, keep_prob

### LSTM Cell

Here we will create the LSTM cell we'll use in the hidden layer. We'll use this cell as a building block for the RNN. So we aren't actually defining the RNN here, just the type of cell we'll use in the hidden layer.

We first create a basic LSTM cell with

```python
lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
```

where `num_units` is the number of units in the hidden layers in the cell. Then we can add dropout by wrapping it with 

```python
tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
```
You pass in a cell and it will automatically add dropout to the inputs or outputs. Finally, we can stack up the LSTM cells into layers with [`tf.contrib.rnn.MultiRNNCell`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/contrib/rnn/MultiRNNCell). With this, you pass in a list of cells and it will send the output of one cell into the next cell. Previously with TensorFlow 1.0, you could do this

```python
tf.contrib.rnn.MultiRNNCell([cell]*num_layers)
```

This might look a little weird if you know Python well because this will create a list of the same `cell` object. However, TensorFlow 1.0 will create different weight matrices for all `cell` objects. But, starting with TensorFlow 1.1 you actually need to create new cell objects in the list. To get it to work in TensorFlow 1.1, it should look like

```python
def build_cell(num_units, keep_prob):
    lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
    drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
    
    return drop
    
tf.contrib.rnn.MultiRNNCell([build_cell(num_units, keep_prob) for _ in range(num_layers)])
```

Even though this is actually multiple LSTM cells stacked on each other, you can treat the multiple layers as one cell.

We also need to create an initial cell state of all zeros. This can be done like so

```python
initial_state = cell.zero_state(batch_size, tf.float32)
```

Below, we implement the `build_lstm` function to create these LSTM cells and the initial state.

In [10]:
def build_cell(num_units, keep_prob):
    lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
    drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)

    return drop

def build_lstm(lstm_size, num_layers, batch_size, keep_prob):
    ''' Build LSTM cell.
    
        Arguments
        ---------
        keep_prob: Scalar tensor (tf.placeholder) for the dropout keep probability
        lstm_size: Size of the hidden layers in the LSTM cells
        num_layers: Number of LSTM layers
        batch_size: Batch size

    '''
    ### Build the LSTM Cell
    # Use a basic LSTM cell
    #lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
    
    # Add dropout to the cell outputs
    #drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
    
    # Stack up multiple LSTM layers, for deep learning
    cell = tf.contrib.rnn.MultiRNNCell([build_cell(lstm_size, keep_prob) for _ in range(num_layers)])
    initial_state = cell.zero_state(batch_size, tf.float32)

    
    return cell, initial_state

### RNN Output

Here we'll create the output layer. We need to connect the output of the RNN cells to a full connected layer with a softmax output. The softmax output gives us a probability distribution we can use to predict the next character, so we want this layer to have size $C$, the number of classes/characters we have in our text.

If our input has batch size $N$, number of steps $M$, and the hidden layer has $L$ hidden units, then the output is a 3D tensor with size $N \times M \times L$. The output of each LSTM cell has size $L$, we have $M$ of them, one for each sequence step, and we have $N$ sequences. So the total size is $N \times M \times L$. 

We are using the same fully connected layer, the same weights, for each of the outputs. Then, to make things easier, we should reshape the outputs into a 2D tensor with shape $(M * N) \times L$. That is, one row for each sequence and step, where the values of each row are the output from the LSTM cells. We get the LSTM output as a list, `lstm_output`. First we need to concatenate this whole list into one array with [`tf.concat`](https://www.tensorflow.org/api_docs/python/tf/concat). Then, reshape it (with `tf.reshape`) to size $(M * N) \times L$.

One we have the outputs reshaped, we can do the matrix multiplication with the weights. We need to wrap the weight and bias variables in a variable scope with `tf.variable_scope(scope_name)` because there are weights being created in the LSTM cells. TensorFlow will throw an error if the weights created here have the same names as the weights created in the LSTM cells, which they will be default. To avoid this, we wrap the variables in a variable scope so we can give them unique names.

> **Exercise:** Implement the output layer in the function below.

In [11]:
def build_output(lstm_output, in_size, out_size):
    ''' Build a softmax layer, return the softmax output and logits.
    
        Arguments
        ---------
        
        lstm_output: List of output tensors from the LSTM layer
        in_size: Size of the input tensor, for example, size of the LSTM cells
        out_size: Size of this softmax layer
    
    '''

    # Reshape output so it's a bunch of rows, one row for each step for each sequence.
    # Concatenate lstm_output over axis 1 (the columns)
    seq_output = tf.concat(lstm_output, axis=1)
    # Reshape seq_output to a 2D tensor with lstm_size columns
    x = tf.reshape(seq_output, [-1, in_size])
    
    # Connect the RNN outputs to a softmax layer
    with tf.variable_scope('softmax'):
        # Create the weight and bias variables here
        softmax_w = tf.Variable(tf.truncated_normal([in_size, out_size], stddev = 0.1, name = 'softmax_w'))
        softmax_b = tf.Variable(tf.zeros(out_size), name = 'softmax_b')
    
    # Since output is a bunch of rows of RNN cell outputs, logits will be a bunch
    # of rows of logit outputs, one for each step and sequence
    logits = tf.add(tf.matmul(x, softmax_w), softmax_b)
    
    # Use softmax to get the probabilities for predicted characters
    out = tf.nn.softmax(logits, name='predictions')
    
    return out, logits

### Training loss

Next up is the training loss. We get the logits and targets and calculate the softmax cross-entropy loss. First we need to one-hot encode the targets, we're getting them as encoded characters. Then, reshape the one-hot targets so it's a 2D tensor with size $(M*N) \times C$ where $C$ is the number of classes/characters we have. Remember that we reshaped the LSTM outputs and ran them through a fully connected layer with $C$ units. So our logits will also have size $(M*N) \times C$.

Then we run the logits and targets through `tf.nn.softmax_cross_entropy_with_logits` and find the mean to get the loss.

>**Exercise:** Implement the loss calculation in the function below.

In [12]:
def build_loss(logits, targets, lstm_size, num_classes):
    ''' Calculate the loss from the logits and the targets.
    
        Arguments
        ---------
        logits: Logits from final fully connected layer
        targets: Targets for supervised learning
        lstm_size: Number of LSTM hidden units
        num_classes: Number of classes in targets
        
    '''
    
    # One-hot encode targets and reshape to match logits, one row per sequence per step
    y_one_hot = tf.one_hot(targets, num_classes)
    y_reshaped = tf.reshape(y_one_hot, logits.get_shape())
    
    # Softmax cross entropy loss
    softmax = tf.nn.softmax_cross_entropy_with_logits(logits = logits, labels = y_reshaped)
    loss = tf.reduce_mean(softmax)
    return loss

### Optimizer

Here we build the optimizer. Normal RNNs have have issues gradients exploding and disappearing. LSTMs fix the disappearance problem, but the gradients can still grow without bound. To fix this, we can clip the gradients above some threshold. That is, if a gradient is larger than that threshold, we set it to the threshold. This will ensure the gradients never grow overly large. Then we use an AdamOptimizer for the learning step.

In [13]:
def build_optimizer(loss, learning_rate, grad_clip):
    ''' Build optmizer for training, using gradient clipping.
    
        Arguments:
        loss: Network loss
        learning_rate: Learning rate for optimizer
    
    '''
    
    # Optimizer for training, using gradient clipping to control exploding gradients
    tvars = tf.trainable_variables()
    grads, _ = tf.clip_by_global_norm(tf.gradients(loss, tvars), grad_clip)
    train_op = tf.train.AdamOptimizer(learning_rate)
    optimizer = train_op.apply_gradients(zip(grads, tvars))
    
    return optimizer

### Build the network

Now we can put all the pieces together and build a class for the network. To actually run data through the LSTM cells, we will use [`tf.nn.dynamic_rnn`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/nn/dynamic_rnn). This function will pass the hidden and cell states across LSTM cells appropriately for us. It returns the outputs for each LSTM cell at each step for each sequence in the mini-batch. It also gives us the final LSTM state. We want to save this state as `final_state` so we can pass it to the first LSTM cell in the the next mini-batch run. For `tf.nn.dynamic_rnn`, we pass in the cell and initial state we get from `build_lstm`, as well as our input sequences. Also, we need to one-hot encode the inputs before going into the RNN. 

> **Exercise:** Use the functions you've implemented previously and `tf.nn.dynamic_rnn` to build the network.

In [14]:
class CharRNN:
    
    def __init__(self, num_classes, batch_size=64, num_steps=50, 
                       lstm_size=128, num_layers=2, learning_rate=0.001, 
                       grad_clip=5, sampling=False):
    
        # When we're using this network for sampling later, we'll be passing in
        # one character at a time, so providing an option for that
        if sampling == True:
            batch_size, num_steps = 1, 1
        else:
            batch_size, num_steps = batch_size, num_steps

        tf.reset_default_graph()
        
        # Build the input placeholder tensors
        self.inputs, self.targets, self.keep_prob = build_inputs(batch_size, num_steps)

        # Build the LSTM cell
        cell, self.initial_state = build_lstm(lstm_size, num_layers, batch_size, self.keep_prob)

        ### Run the data through the RNN layers
        # First, one-hot encode the input tokens
        x_one_hot = tf.one_hot(self.inputs, num_classes)
        
        # Run each sequence step through the RNN with tf.nn.dynamic_rnn 
        outputs, state = tf.nn.dynamic_rnn(cell, x_one_hot, initial_state=self.initial_state)
        self.final_state = state
        
        # Get softmax predictions and logits
        self.prediction, self.logits = build_output(outputs, lstm_size, num_classes)
        
        # Loss and optimizer (with gradient clipping)
        self.loss = build_loss(self.logits, self.targets, lstm_size, num_classes)
        self.optimizer = build_optimizer(self.loss, learning_rate, grad_clip)

## Hyperparameters

Here are the hyperparameters for the network.

* `batch_size` - Number of sequences running through the network in one pass.
* `num_steps` - Number of characters in the sequence the network is trained on. Larger is better typically, the network will learn more long range dependencies. But it takes longer to train. 100 is typically a good number here.
* `lstm_size` - The number of units in the hidden layers.
* `num_layers` - Number of hidden LSTM layers to use
* `learning_rate` - Learning rate for training
* `keep_prob` - The dropout keep probability when training. If you're network is overfitting, try decreasing this.

Here's some good advice from Andrej Karpathy on training the network. I'm going to copy it in here for your benefit, but also link to [where it originally came from](https://github.com/karpathy/char-rnn#tips-and-tricks).

> ## Tips and Tricks

>### Monitoring Validation Loss vs. Training Loss
>If you're somewhat new to Machine Learning or Neural Networks it can take a bit of expertise to get good models. The most important quantity to keep track of is the difference between your training loss (printed during training) and the validation loss (printed once in a while when the RNN is run on the validation data (by default every 1000 iterations)). In particular:

> - If your training loss is much lower than validation loss then this means the network might be **overfitting**. Solutions to this are to decrease your network size, or to increase dropout. For example you could try dropout of 0.5 and so on.
> - If your training/validation loss are about equal then your model is **underfitting**. Increase the size of your model (either number of layers or the raw number of neurons per layer)

> ### Approximate number of parameters

> The two most important parameters that control the model are `lstm_size` and `num_layers`. I would advise that you always use `num_layers` of either 2/3. The `lstm_size` can be adjusted based on how much data you have. The two important quantities to keep track of here are:

> - The number of parameters in your model. This is printed when you start training.
> - The size of your dataset. 1MB file is approximately 1 million characters.

>These two should be about the same order of magnitude. It's a little tricky to tell. Here are some examples:

> - I have a 100MB dataset and I'm using the default parameter settings (which currently print 150K parameters). My data size is significantly larger (100 mil >> 0.15 mil), so I expect to heavily underfit. I am thinking I can comfortably afford to make `lstm_size` larger.
> - I have a 10MB dataset and running a 10 million parameter model. I'm slightly nervous and I'm carefully monitoring my validation loss. If it's larger than my training loss then I may want to try to increase dropout a bit and see if that helps the validation loss.

> ### Best models strategy

>The winning strategy to obtaining very good models (if you have the compute time) is to always err on making the network larger (as large as you're willing to wait for it to compute) and then try different dropout values (between 0,1). Whatever model has the best validation performance (the loss, written in the checkpoint filename, low is good) is the one you should use in the end.

>It is very common in deep learning to run many different models with many different hyperparameter settings, and in the end take whatever checkpoint gave the best validation performance.

>By the way, the size of your training and validation splits are also parameters. Make sure you have a decent amount of data in your validation set or otherwise the validation performance will be noisy and not very informative.

In [15]:
batch_size = 10         # Sequences per batch
num_steps = 50          # Number of sequence steps per batch
lstm_size = 128         # Size of hidden layers in LSTMs
num_layers = 2          # Number of LSTM layers
learning_rate = 0.01    # Learning rate
keep_prob = 0.5         # Dropout keep probability

## Time for training

This is typical training code, passing inputs and targets into the network, then running the optimizer. Here we also get back the final LSTM state for the mini-batch. Then, we pass that state back into the network so the next batch can continue the state from the previous batch. And every so often (set by `save_every_n`) I save a checkpoint.

Here I'm saving checkpoints with the format

`i{iteration number}_l{# hidden layer units}.ckpt`

> **Exercise:** Set the hyperparameters above to train the network. Watch the training loss, it should be consistently dropping. Also, I highly advise running this on a GPU.

In [16]:
epochs = 20
# Save every N iterations
save_every_n = 200

model = CharRNN(len(vocab), batch_size=batch_size, num_steps=num_steps,
                lstm_size=lstm_size, num_layers=num_layers, 
                learning_rate=learning_rate)

saver = tf.train.Saver(max_to_keep=100)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    # Use the line below to load a checkpoint and resume training
    #saver.restore(sess, 'checkpoints/______.ckpt')
    counter = 0
    for e in range(epochs):
        # Train network
        new_state = sess.run(model.initial_state)
        loss = 0
        for x, y in get_batches(encoded, batch_size, num_steps):
            counter += 1
            start = time.time()
            feed = {model.inputs: x,
                    model.targets: y,
                    model.keep_prob: keep_prob,
                    model.initial_state: new_state}
            batch_loss, new_state, _ = sess.run([model.loss, 
                                                 model.final_state, 
                                                 model.optimizer], 
                                                 feed_dict=feed)
            
            end = time.time()
            print('Epoch: {}/{}... '.format(e+1, epochs),
                  'Training Step: {}... '.format(counter),
                  'Training loss: {:.4f}... '.format(batch_loss),
                  '{:.4f} sec/batch'.format((end-start)))
        
            if (counter % save_every_n == 0):
                saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))
    
    saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))

Epoch: 1/20...  Training Step: 1...  Training loss: 4.4191...  0.4879 sec/batch
Epoch: 1/20...  Training Step: 2...  Training loss: 4.2572...  0.0873 sec/batch
Epoch: 1/20...  Training Step: 3...  Training loss: 3.4757...  0.0636 sec/batch
Epoch: 1/20...  Training Step: 4...  Training loss: 3.4404...  0.0469 sec/batch
Epoch: 1/20...  Training Step: 5...  Training loss: 3.2333...  0.0627 sec/batch
Epoch: 1/20...  Training Step: 6...  Training loss: 3.4126...  0.0604 sec/batch
Epoch: 1/20...  Training Step: 7...  Training loss: 3.2230...  0.0510 sec/batch
Epoch: 1/20...  Training Step: 8...  Training loss: 3.1848...  0.0600 sec/batch
Epoch: 1/20...  Training Step: 9...  Training loss: 3.2651...  0.0886 sec/batch
Epoch: 1/20...  Training Step: 10...  Training loss: 3.2420...  0.0923 sec/batch
Epoch: 1/20...  Training Step: 11...  Training loss: 3.2903...  0.0808 sec/batch
Epoch: 1/20...  Training Step: 12...  Training loss: 3.1800...  0.0938 sec/batch
Epoch: 1/20...  Training Step: 13... 

Epoch: 1/20...  Training Step: 106...  Training loss: 2.9376...  0.0482 sec/batch
Epoch: 1/20...  Training Step: 107...  Training loss: 2.7358...  0.0538 sec/batch
Epoch: 1/20...  Training Step: 108...  Training loss: 2.7764...  0.0548 sec/batch
Epoch: 1/20...  Training Step: 109...  Training loss: 2.7423...  0.0639 sec/batch
Epoch: 1/20...  Training Step: 110...  Training loss: 2.7823...  0.0713 sec/batch
Epoch: 1/20...  Training Step: 111...  Training loss: 2.6941...  0.0546 sec/batch
Epoch: 1/20...  Training Step: 112...  Training loss: 2.7336...  0.0534 sec/batch
Epoch: 1/20...  Training Step: 113...  Training loss: 2.6919...  0.0470 sec/batch
Epoch: 1/20...  Training Step: 114...  Training loss: 2.6648...  0.0487 sec/batch
Epoch: 1/20...  Training Step: 115...  Training loss: 2.7642...  0.0670 sec/batch
Epoch: 1/20...  Training Step: 116...  Training loss: 2.7623...  0.0499 sec/batch
Epoch: 1/20...  Training Step: 117...  Training loss: 2.6715...  0.0523 sec/batch
Epoch: 1/20...  

Epoch: 1/20...  Training Step: 206...  Training loss: 2.4214...  0.0683 sec/batch
Epoch: 1/20...  Training Step: 207...  Training loss: 2.5177...  0.0522 sec/batch
Epoch: 1/20...  Training Step: 208...  Training loss: 2.4673...  0.0507 sec/batch
Epoch: 1/20...  Training Step: 209...  Training loss: 2.4608...  0.0529 sec/batch
Epoch: 1/20...  Training Step: 210...  Training loss: 2.4289...  0.0441 sec/batch
Epoch: 1/20...  Training Step: 211...  Training loss: 2.4435...  0.0633 sec/batch
Epoch: 1/20...  Training Step: 212...  Training loss: 2.4557...  0.1064 sec/batch
Epoch: 1/20...  Training Step: 213...  Training loss: 2.4817...  0.0869 sec/batch
Epoch: 1/20...  Training Step: 214...  Training loss: 2.4961...  0.0909 sec/batch
Epoch: 1/20...  Training Step: 215...  Training loss: 2.4400...  0.0922 sec/batch
Epoch: 1/20...  Training Step: 216...  Training loss: 2.3657...  0.0610 sec/batch
Epoch: 1/20...  Training Step: 217...  Training loss: 2.5582...  0.0564 sec/batch
Epoch: 1/20...  

Epoch: 1/20...  Training Step: 307...  Training loss: 2.3713...  0.0959 sec/batch
Epoch: 1/20...  Training Step: 308...  Training loss: 2.3009...  0.0840 sec/batch
Epoch: 1/20...  Training Step: 309...  Training loss: 2.3367...  0.0458 sec/batch
Epoch: 1/20...  Training Step: 310...  Training loss: 2.3368...  0.0515 sec/batch
Epoch: 1/20...  Training Step: 311...  Training loss: 2.3818...  0.0859 sec/batch
Epoch: 1/20...  Training Step: 312...  Training loss: 2.2900...  0.0854 sec/batch
Epoch: 1/20...  Training Step: 313...  Training loss: 2.2496...  0.0837 sec/batch
Epoch: 1/20...  Training Step: 314...  Training loss: 2.3238...  0.0960 sec/batch
Epoch: 1/20...  Training Step: 315...  Training loss: 2.3159...  0.0485 sec/batch
Epoch: 1/20...  Training Step: 316...  Training loss: 2.3526...  0.0486 sec/batch
Epoch: 1/20...  Training Step: 317...  Training loss: 2.3911...  0.0472 sec/batch
Epoch: 1/20...  Training Step: 318...  Training loss: 2.3903...  0.0444 sec/batch
Epoch: 1/20...  

Epoch: 1/20...  Training Step: 411...  Training loss: 2.2193...  0.0600 sec/batch
Epoch: 1/20...  Training Step: 412...  Training loss: 2.2425...  0.0508 sec/batch
Epoch: 1/20...  Training Step: 413...  Training loss: 2.3759...  0.0516 sec/batch
Epoch: 1/20...  Training Step: 414...  Training loss: 2.1743...  0.0482 sec/batch
Epoch: 1/20...  Training Step: 415...  Training loss: 2.1818...  0.0441 sec/batch
Epoch: 1/20...  Training Step: 416...  Training loss: 2.2197...  0.0594 sec/batch
Epoch: 1/20...  Training Step: 417...  Training loss: 2.2607...  0.0562 sec/batch
Epoch: 1/20...  Training Step: 418...  Training loss: 2.1552...  0.0533 sec/batch
Epoch: 1/20...  Training Step: 419...  Training loss: 2.1867...  0.0435 sec/batch
Epoch: 1/20...  Training Step: 420...  Training loss: 2.2277...  0.0487 sec/batch
Epoch: 1/20...  Training Step: 421...  Training loss: 2.2657...  0.0579 sec/batch
Epoch: 1/20...  Training Step: 422...  Training loss: 2.2302...  0.0548 sec/batch
Epoch: 1/20...  

Epoch: 1/20...  Training Step: 515...  Training loss: 2.2298...  0.0647 sec/batch
Epoch: 1/20...  Training Step: 516...  Training loss: 2.2387...  0.0510 sec/batch
Epoch: 1/20...  Training Step: 517...  Training loss: 2.3100...  0.0516 sec/batch
Epoch: 1/20...  Training Step: 518...  Training loss: 2.1224...  0.0430 sec/batch
Epoch: 1/20...  Training Step: 519...  Training loss: 2.1985...  0.0485 sec/batch
Epoch: 1/20...  Training Step: 520...  Training loss: 2.2045...  0.0608 sec/batch
Epoch: 1/20...  Training Step: 521...  Training loss: 2.0588...  0.0521 sec/batch
Epoch: 1/20...  Training Step: 522...  Training loss: 2.1642...  0.0450 sec/batch
Epoch: 1/20...  Training Step: 523...  Training loss: 2.1418...  0.0453 sec/batch
Epoch: 1/20...  Training Step: 524...  Training loss: 2.1304...  0.0501 sec/batch
Epoch: 1/20...  Training Step: 525...  Training loss: 2.1510...  0.0632 sec/batch
Epoch: 1/20...  Training Step: 526...  Training loss: 2.1143...  0.0511 sec/batch
Epoch: 1/20...  

Epoch: 1/20...  Training Step: 616...  Training loss: 2.0473...  0.0617 sec/batch
Epoch: 1/20...  Training Step: 617...  Training loss: 2.1007...  0.0517 sec/batch
Epoch: 1/20...  Training Step: 618...  Training loss: 2.0691...  0.0432 sec/batch
Epoch: 1/20...  Training Step: 619...  Training loss: 2.0159...  0.0483 sec/batch
Epoch: 1/20...  Training Step: 620...  Training loss: 2.0358...  0.0472 sec/batch
Epoch: 1/20...  Training Step: 621...  Training loss: 1.9982...  0.0646 sec/batch
Epoch: 1/20...  Training Step: 622...  Training loss: 2.1056...  0.0464 sec/batch
Epoch: 1/20...  Training Step: 623...  Training loss: 2.1862...  0.0452 sec/batch
Epoch: 1/20...  Training Step: 624...  Training loss: 2.1178...  0.0518 sec/batch
Epoch: 1/20...  Training Step: 625...  Training loss: 2.1007...  0.0518 sec/batch
Epoch: 1/20...  Training Step: 626...  Training loss: 2.1407...  0.0608 sec/batch
Epoch: 1/20...  Training Step: 627...  Training loss: 2.0890...  0.0570 sec/batch
Epoch: 1/20...  

Epoch: 1/20...  Training Step: 719...  Training loss: 2.0321...  0.0443 sec/batch
Epoch: 1/20...  Training Step: 720...  Training loss: 2.1515...  0.0573 sec/batch
Epoch: 1/20...  Training Step: 721...  Training loss: 2.1035...  0.0493 sec/batch
Epoch: 1/20...  Training Step: 722...  Training loss: 2.0346...  0.0509 sec/batch
Epoch: 1/20...  Training Step: 723...  Training loss: 2.1479...  0.0432 sec/batch
Epoch: 1/20...  Training Step: 724...  Training loss: 2.0932...  0.0577 sec/batch
Epoch: 1/20...  Training Step: 725...  Training loss: 2.0384...  0.0487 sec/batch
Epoch: 1/20...  Training Step: 726...  Training loss: 2.1375...  0.0521 sec/batch
Epoch: 1/20...  Training Step: 727...  Training loss: 2.0917...  0.0445 sec/batch
Epoch: 1/20...  Training Step: 728...  Training loss: 2.0568...  0.0587 sec/batch
Epoch: 1/20...  Training Step: 729...  Training loss: 2.0383...  0.0500 sec/batch
Epoch: 1/20...  Training Step: 730...  Training loss: 2.0778...  0.0511 sec/batch
Epoch: 1/20...  

Epoch: 1/20...  Training Step: 821...  Training loss: 2.0282...  0.0549 sec/batch
Epoch: 1/20...  Training Step: 822...  Training loss: 2.1345...  0.0584 sec/batch
Epoch: 1/20...  Training Step: 823...  Training loss: 1.9651...  0.0516 sec/batch
Epoch: 1/20...  Training Step: 824...  Training loss: 1.9958...  0.0420 sec/batch
Epoch: 1/20...  Training Step: 825...  Training loss: 1.9786...  0.0516 sec/batch
Epoch: 1/20...  Training Step: 826...  Training loss: 2.0572...  0.0566 sec/batch
Epoch: 1/20...  Training Step: 827...  Training loss: 1.9886...  0.0518 sec/batch
Epoch: 1/20...  Training Step: 828...  Training loss: 2.1111...  0.0436 sec/batch
Epoch: 1/20...  Training Step: 829...  Training loss: 2.0503...  0.0486 sec/batch
Epoch: 1/20...  Training Step: 830...  Training loss: 2.0395...  0.0573 sec/batch
Epoch: 1/20...  Training Step: 831...  Training loss: 2.0822...  0.0515 sec/batch
Epoch: 1/20...  Training Step: 832...  Training loss: 2.0280...  0.0482 sec/batch
Epoch: 1/20...  

Epoch: 1/20...  Training Step: 924...  Training loss: 1.9942...  0.0449 sec/batch
Epoch: 1/20...  Training Step: 925...  Training loss: 2.0255...  0.0556 sec/batch
Epoch: 1/20...  Training Step: 926...  Training loss: 2.0113...  0.0476 sec/batch
Epoch: 1/20...  Training Step: 927...  Training loss: 2.0399...  0.0522 sec/batch
Epoch: 1/20...  Training Step: 928...  Training loss: 2.0290...  0.0481 sec/batch
Epoch: 1/20...  Training Step: 929...  Training loss: 1.9447...  0.0578 sec/batch
Epoch: 1/20...  Training Step: 930...  Training loss: 2.0075...  0.0502 sec/batch
Epoch: 1/20...  Training Step: 931...  Training loss: 2.1164...  0.0534 sec/batch
Epoch: 1/20...  Training Step: 932...  Training loss: 1.9381...  0.0534 sec/batch
Epoch: 1/20...  Training Step: 933...  Training loss: 2.0143...  0.0549 sec/batch
Epoch: 1/20...  Training Step: 934...  Training loss: 2.0026...  0.0454 sec/batch
Epoch: 1/20...  Training Step: 935...  Training loss: 2.0633...  0.0487 sec/batch
Epoch: 1/20...  

Epoch: 1/20...  Training Step: 1026...  Training loss: 2.1495...  0.0569 sec/batch
Epoch: 1/20...  Training Step: 1027...  Training loss: 2.0446...  0.0453 sec/batch
Epoch: 1/20...  Training Step: 1028...  Training loss: 2.0036...  0.0495 sec/batch
Epoch: 1/20...  Training Step: 1029...  Training loss: 2.0372...  0.0524 sec/batch
Epoch: 1/20...  Training Step: 1030...  Training loss: 1.9578...  0.0435 sec/batch
Epoch: 1/20...  Training Step: 1031...  Training loss: 1.9644...  0.0578 sec/batch
Epoch: 1/20...  Training Step: 1032...  Training loss: 1.9272...  0.0493 sec/batch
Epoch: 1/20...  Training Step: 1033...  Training loss: 1.9614...  0.0518 sec/batch
Epoch: 1/20...  Training Step: 1034...  Training loss: 2.0646...  0.0451 sec/batch
Epoch: 1/20...  Training Step: 1035...  Training loss: 2.0397...  0.0452 sec/batch
Epoch: 1/20...  Training Step: 1036...  Training loss: 2.0920...  0.0605 sec/batch
Epoch: 1/20...  Training Step: 1037...  Training loss: 1.9278...  0.0516 sec/batch
Epoc

Epoch: 1/20...  Training Step: 1126...  Training loss: 1.9970...  0.0615 sec/batch
Epoch: 1/20...  Training Step: 1127...  Training loss: 2.0438...  0.0481 sec/batch
Epoch: 1/20...  Training Step: 1128...  Training loss: 1.9270...  0.0527 sec/batch
Epoch: 1/20...  Training Step: 1129...  Training loss: 1.9934...  0.0452 sec/batch
Epoch: 1/20...  Training Step: 1130...  Training loss: 1.9635...  0.0467 sec/batch
Epoch: 1/20...  Training Step: 1131...  Training loss: 1.9572...  0.0609 sec/batch
Epoch: 1/20...  Training Step: 1132...  Training loss: 1.7730...  0.0507 sec/batch
Epoch: 1/20...  Training Step: 1133...  Training loss: 1.9283...  0.0495 sec/batch
Epoch: 1/20...  Training Step: 1134...  Training loss: 2.0623...  0.0431 sec/batch
Epoch: 1/20...  Training Step: 1135...  Training loss: 1.8625...  0.0478 sec/batch
Epoch: 1/20...  Training Step: 1136...  Training loss: 2.0445...  0.0625 sec/batch
Epoch: 1/20...  Training Step: 1137...  Training loss: 2.0453...  0.0525 sec/batch
Epoc

Epoch: 1/20...  Training Step: 1226...  Training loss: 1.9675...  0.0497 sec/batch
Epoch: 1/20...  Training Step: 1227...  Training loss: 2.0829...  0.0576 sec/batch
Epoch: 1/20...  Training Step: 1228...  Training loss: 2.0269...  0.0528 sec/batch
Epoch: 1/20...  Training Step: 1229...  Training loss: 1.8658...  0.0482 sec/batch
Epoch: 1/20...  Training Step: 1230...  Training loss: 2.0639...  0.0492 sec/batch
Epoch: 1/20...  Training Step: 1231...  Training loss: 1.8599...  0.0567 sec/batch
Epoch: 1/20...  Training Step: 1232...  Training loss: 2.0903...  0.0521 sec/batch
Epoch: 1/20...  Training Step: 1233...  Training loss: 1.9809...  0.0532 sec/batch
Epoch: 1/20...  Training Step: 1234...  Training loss: 2.0578...  0.0446 sec/batch
Epoch: 1/20...  Training Step: 1235...  Training loss: 1.9222...  0.0573 sec/batch
Epoch: 1/20...  Training Step: 1236...  Training loss: 1.9543...  0.0499 sec/batch
Epoch: 1/20...  Training Step: 1237...  Training loss: 1.9944...  0.0527 sec/batch
Epoc

Epoch: 1/20...  Training Step: 1328...  Training loss: 1.9309...  0.0508 sec/batch
Epoch: 1/20...  Training Step: 1329...  Training loss: 2.0104...  0.0604 sec/batch
Epoch: 1/20...  Training Step: 1330...  Training loss: 2.0377...  0.0532 sec/batch
Epoch: 1/20...  Training Step: 1331...  Training loss: 2.0103...  0.0521 sec/batch
Epoch: 1/20...  Training Step: 1332...  Training loss: 1.9207...  0.0448 sec/batch
Epoch: 1/20...  Training Step: 1333...  Training loss: 1.9199...  0.0579 sec/batch
Epoch: 1/20...  Training Step: 1334...  Training loss: 2.0282...  0.0490 sec/batch
Epoch: 1/20...  Training Step: 1335...  Training loss: 1.8861...  0.0510 sec/batch
Epoch: 1/20...  Training Step: 1336...  Training loss: 1.9434...  0.0443 sec/batch
Epoch: 1/20...  Training Step: 1337...  Training loss: 1.9291...  0.0583 sec/batch
Epoch: 1/20...  Training Step: 1338...  Training loss: 2.0349...  0.0507 sec/batch
Epoch: 1/20...  Training Step: 1339...  Training loss: 1.9709...  0.0516 sec/batch
Epoc

Epoch: 1/20...  Training Step: 1428...  Training loss: 2.0769...  0.0493 sec/batch
Epoch: 1/20...  Training Step: 1429...  Training loss: 1.9360...  0.0567 sec/batch
Epoch: 1/20...  Training Step: 1430...  Training loss: 2.0000...  0.0531 sec/batch
Epoch: 1/20...  Training Step: 1431...  Training loss: 1.9180...  0.0436 sec/batch
Epoch: 1/20...  Training Step: 1432...  Training loss: 1.9792...  0.0500 sec/batch
Epoch: 1/20...  Training Step: 1433...  Training loss: 2.1084...  0.0600 sec/batch
Epoch: 1/20...  Training Step: 1434...  Training loss: 1.9324...  0.0512 sec/batch
Epoch: 1/20...  Training Step: 1435...  Training loss: 1.9564...  0.0461 sec/batch
Epoch: 1/20...  Training Step: 1436...  Training loss: 1.9584...  0.0470 sec/batch
Epoch: 1/20...  Training Step: 1437...  Training loss: 2.0058...  0.0582 sec/batch
Epoch: 1/20...  Training Step: 1438...  Training loss: 2.0251...  0.0502 sec/batch
Epoch: 1/20...  Training Step: 1439...  Training loss: 2.0184...  0.0526 sec/batch
Epoc

Epoch: 1/20...  Training Step: 1528...  Training loss: 1.9833...  0.0525 sec/batch
Epoch: 1/20...  Training Step: 1529...  Training loss: 2.0144...  0.0583 sec/batch
Epoch: 1/20...  Training Step: 1530...  Training loss: 2.0005...  0.0521 sec/batch
Epoch: 1/20...  Training Step: 1531...  Training loss: 2.0326...  0.0430 sec/batch
Epoch: 1/20...  Training Step: 1532...  Training loss: 2.0820...  0.0492 sec/batch
Epoch: 1/20...  Training Step: 1533...  Training loss: 1.9374...  0.0588 sec/batch
Epoch: 1/20...  Training Step: 1534...  Training loss: 1.9349...  0.0533 sec/batch
Epoch: 1/20...  Training Step: 1535...  Training loss: 1.9966...  0.0426 sec/batch
Epoch: 1/20...  Training Step: 1536...  Training loss: 1.9066...  0.0519 sec/batch
Epoch: 1/20...  Training Step: 1537...  Training loss: 1.8841...  0.0598 sec/batch
Epoch: 1/20...  Training Step: 1538...  Training loss: 1.9478...  0.0533 sec/batch
Epoch: 1/20...  Training Step: 1539...  Training loss: 2.1747...  0.0444 sec/batch
Epoc

Epoch: 1/20...  Training Step: 1629...  Training loss: 2.0393...  0.0544 sec/batch
Epoch: 1/20...  Training Step: 1630...  Training loss: 1.9874...  0.0587 sec/batch
Epoch: 1/20...  Training Step: 1631...  Training loss: 1.9197...  0.0432 sec/batch
Epoch: 1/20...  Training Step: 1632...  Training loss: 1.8257...  0.0498 sec/batch
Epoch: 1/20...  Training Step: 1633...  Training loss: 1.9377...  0.0506 sec/batch
Epoch: 1/20...  Training Step: 1634...  Training loss: 1.9025...  0.0638 sec/batch
Epoch: 1/20...  Training Step: 1635...  Training loss: 1.9179...  0.0446 sec/batch
Epoch: 1/20...  Training Step: 1636...  Training loss: 1.9737...  0.0469 sec/batch
Epoch: 1/20...  Training Step: 1637...  Training loss: 1.9196...  0.0520 sec/batch
Epoch: 1/20...  Training Step: 1638...  Training loss: 1.8596...  0.0581 sec/batch
Epoch: 1/20...  Training Step: 1639...  Training loss: 1.9028...  0.0484 sec/batch
Epoch: 1/20...  Training Step: 1640...  Training loss: 2.0038...  0.0439 sec/batch
Epoc

Epoch: 1/20...  Training Step: 1730...  Training loss: 1.7975...  0.0531 sec/batch
Epoch: 1/20...  Training Step: 1731...  Training loss: 1.9418...  0.0595 sec/batch
Epoch: 1/20...  Training Step: 1732...  Training loss: 2.0095...  0.0466 sec/batch
Epoch: 1/20...  Training Step: 1733...  Training loss: 2.0670...  0.0483 sec/batch
Epoch: 1/20...  Training Step: 1734...  Training loss: 2.0527...  0.0556 sec/batch
Epoch: 1/20...  Training Step: 1735...  Training loss: 1.9937...  0.0659 sec/batch
Epoch: 1/20...  Training Step: 1736...  Training loss: 1.8953...  0.0625 sec/batch
Epoch: 1/20...  Training Step: 1737...  Training loss: 1.8615...  0.0524 sec/batch
Epoch: 1/20...  Training Step: 1738...  Training loss: 1.9395...  0.0461 sec/batch
Epoch: 1/20...  Training Step: 1739...  Training loss: 1.9859...  0.0728 sec/batch
Epoch: 1/20...  Training Step: 1740...  Training loss: 1.9537...  0.0910 sec/batch
Epoch: 1/20...  Training Step: 1741...  Training loss: 1.9696...  0.0599 sec/batch
Epoc

Epoch: 1/20...  Training Step: 1829...  Training loss: 1.9759...  0.0484 sec/batch
Epoch: 1/20...  Training Step: 1830...  Training loss: 1.8402...  0.0606 sec/batch
Epoch: 1/20...  Training Step: 1831...  Training loss: 1.9603...  0.0515 sec/batch
Epoch: 1/20...  Training Step: 1832...  Training loss: 1.9799...  0.0431 sec/batch
Epoch: 1/20...  Training Step: 1833...  Training loss: 1.9097...  0.0537 sec/batch
Epoch: 1/20...  Training Step: 1834...  Training loss: 1.9359...  0.0577 sec/batch
Epoch: 1/20...  Training Step: 1835...  Training loss: 1.8713...  0.0513 sec/batch
Epoch: 1/20...  Training Step: 1836...  Training loss: 1.8969...  0.0448 sec/batch
Epoch: 1/20...  Training Step: 1837...  Training loss: 1.8842...  0.0481 sec/batch
Epoch: 1/20...  Training Step: 1838...  Training loss: 1.8719...  0.0572 sec/batch
Epoch: 1/20...  Training Step: 1839...  Training loss: 1.8557...  0.0532 sec/batch
Epoch: 1/20...  Training Step: 1840...  Training loss: 1.8754...  0.0491 sec/batch
Epoc

Epoch: 1/20...  Training Step: 1929...  Training loss: 1.9925...  0.0614 sec/batch
Epoch: 1/20...  Training Step: 1930...  Training loss: 1.9538...  0.0495 sec/batch
Epoch: 1/20...  Training Step: 1931...  Training loss: 1.8930...  0.0518 sec/batch
Epoch: 1/20...  Training Step: 1932...  Training loss: 1.8969...  0.0455 sec/batch
Epoch: 1/20...  Training Step: 1933...  Training loss: 1.8497...  0.0463 sec/batch
Epoch: 1/20...  Training Step: 1934...  Training loss: 2.1430...  0.0626 sec/batch
Epoch: 1/20...  Training Step: 1935...  Training loss: 1.8590...  0.0521 sec/batch
Epoch: 1/20...  Training Step: 1936...  Training loss: 2.0006...  0.0529 sec/batch
Epoch: 1/20...  Training Step: 1937...  Training loss: 2.0509...  0.0428 sec/batch
Epoch: 1/20...  Training Step: 1938...  Training loss: 2.1692...  0.0496 sec/batch
Epoch: 1/20...  Training Step: 1939...  Training loss: 1.9955...  0.0610 sec/batch
Epoch: 1/20...  Training Step: 1940...  Training loss: 2.1596...  0.0525 sec/batch
Epoc

Epoch: 1/20...  Training Step: 2031...  Training loss: 1.8582...  0.0527 sec/batch
Epoch: 1/20...  Training Step: 2032...  Training loss: 1.8865...  0.0577 sec/batch
Epoch: 1/20...  Training Step: 2033...  Training loss: 1.9249...  0.0516 sec/batch
Epoch: 1/20...  Training Step: 2034...  Training loss: 1.9235...  0.0444 sec/batch
Epoch: 1/20...  Training Step: 2035...  Training loss: 1.8610...  0.0473 sec/batch
Epoch: 1/20...  Training Step: 2036...  Training loss: 1.9144...  0.0575 sec/batch
Epoch: 1/20...  Training Step: 2037...  Training loss: 1.7836...  0.0525 sec/batch
Epoch: 1/20...  Training Step: 2038...  Training loss: 1.9464...  0.0492 sec/batch
Epoch: 1/20...  Training Step: 2039...  Training loss: 1.9034...  0.0445 sec/batch
Epoch: 1/20...  Training Step: 2040...  Training loss: 1.9628...  0.0581 sec/batch
Epoch: 1/20...  Training Step: 2041...  Training loss: 1.8204...  0.0504 sec/batch
Epoch: 1/20...  Training Step: 2042...  Training loss: 1.9373...  0.0504 sec/batch
Epoc

Epoch: 1/20...  Training Step: 2131...  Training loss: 1.8547...  0.0476 sec/batch
Epoch: 1/20...  Training Step: 2132...  Training loss: 1.8347...  0.0580 sec/batch
Epoch: 1/20...  Training Step: 2133...  Training loss: 1.9358...  0.0493 sec/batch
Epoch: 1/20...  Training Step: 2134...  Training loss: 1.9010...  0.0527 sec/batch
Epoch: 1/20...  Training Step: 2135...  Training loss: 1.8301...  0.0443 sec/batch
Epoch: 1/20...  Training Step: 2136...  Training loss: 1.8137...  0.0602 sec/batch
Epoch: 1/20...  Training Step: 2137...  Training loss: 1.9018...  0.0499 sec/batch
Epoch: 1/20...  Training Step: 2138...  Training loss: 1.9002...  0.0523 sec/batch
Epoch: 1/20...  Training Step: 2139...  Training loss: 1.9497...  0.0547 sec/batch
Epoch: 1/20...  Training Step: 2140...  Training loss: 1.9298...  0.0608 sec/batch
Epoch: 1/20...  Training Step: 2141...  Training loss: 1.9380...  0.0446 sec/batch
Epoch: 1/20...  Training Step: 2142...  Training loss: 1.9397...  0.0477 sec/batch
Epoc

Epoch: 1/20...  Training Step: 2231...  Training loss: 1.9529...  0.0556 sec/batch
Epoch: 1/20...  Training Step: 2232...  Training loss: 1.8877...  0.0592 sec/batch
Epoch: 1/20...  Training Step: 2233...  Training loss: 1.8610...  0.0487 sec/batch
Epoch: 1/20...  Training Step: 2234...  Training loss: 1.8843...  0.0501 sec/batch
Epoch: 1/20...  Training Step: 2235...  Training loss: 1.7747...  0.0564 sec/batch
Epoch: 1/20...  Training Step: 2236...  Training loss: 1.6730...  0.0611 sec/batch
Epoch: 1/20...  Training Step: 2237...  Training loss: 1.8728...  0.0514 sec/batch
Epoch: 1/20...  Training Step: 2238...  Training loss: 1.7545...  0.0472 sec/batch
Epoch: 1/20...  Training Step: 2239...  Training loss: 1.9548...  0.0537 sec/batch
Epoch: 1/20...  Training Step: 2240...  Training loss: 2.0951...  0.0611 sec/batch
Epoch: 1/20...  Training Step: 2241...  Training loss: 2.0150...  0.0533 sec/batch
Epoch: 1/20...  Training Step: 2242...  Training loss: 1.8970...  0.0518 sec/batch
Epoc

Epoch: 1/20...  Training Step: 2330...  Training loss: 1.7269...  0.0483 sec/batch
Epoch: 1/20...  Training Step: 2331...  Training loss: 1.7331...  0.0578 sec/batch
Epoch: 1/20...  Training Step: 2332...  Training loss: 1.9064...  0.0536 sec/batch
Epoch: 1/20...  Training Step: 2333...  Training loss: 1.8063...  0.0492 sec/batch
Epoch: 1/20...  Training Step: 2334...  Training loss: 1.8407...  0.0563 sec/batch
Epoch: 1/20...  Training Step: 2335...  Training loss: 1.8242...  0.0570 sec/batch
Epoch: 1/20...  Training Step: 2336...  Training loss: 1.8375...  0.0528 sec/batch
Epoch: 1/20...  Training Step: 2337...  Training loss: 2.0371...  0.0551 sec/batch
Epoch: 1/20...  Training Step: 2338...  Training loss: 2.0701...  0.0537 sec/batch
Epoch: 1/20...  Training Step: 2339...  Training loss: 1.8889...  0.0626 sec/batch
Epoch: 1/20...  Training Step: 2340...  Training loss: 1.9964...  0.0545 sec/batch
Epoch: 1/20...  Training Step: 2341...  Training loss: 1.8735...  0.0505 sec/batch
Epoc

Epoch: 1/20...  Training Step: 2430...  Training loss: 1.8514...  0.0493 sec/batch
Epoch: 1/20...  Training Step: 2431...  Training loss: 1.9246...  0.0646 sec/batch
Epoch: 1/20...  Training Step: 2432...  Training loss: 2.0131...  0.0501 sec/batch
Epoch: 1/20...  Training Step: 2433...  Training loss: 1.9732...  0.0485 sec/batch
Epoch: 1/20...  Training Step: 2434...  Training loss: 1.8253...  0.0606 sec/batch
Epoch: 1/20...  Training Step: 2435...  Training loss: 1.7642...  0.0549 sec/batch
Epoch: 1/20...  Training Step: 2436...  Training loss: 1.8854...  0.0520 sec/batch
Epoch: 1/20...  Training Step: 2437...  Training loss: 1.8191...  0.0624 sec/batch
Epoch: 1/20...  Training Step: 2438...  Training loss: 1.9699...  0.0559 sec/batch
Epoch: 1/20...  Training Step: 2439...  Training loss: 1.9328...  0.0509 sec/batch
Epoch: 1/20...  Training Step: 2440...  Training loss: 1.8497...  0.0538 sec/batch
Epoch: 1/20...  Training Step: 2441...  Training loss: 1.8758...  0.0573 sec/batch
Epoc

Epoch: 1/20...  Training Step: 2530...  Training loss: 1.9114...  0.0541 sec/batch
Epoch: 1/20...  Training Step: 2531...  Training loss: 1.8300...  0.0620 sec/batch
Epoch: 1/20...  Training Step: 2532...  Training loss: 1.7711...  0.0419 sec/batch
Epoch: 1/20...  Training Step: 2533...  Training loss: 1.9316...  0.0500 sec/batch
Epoch: 1/20...  Training Step: 2534...  Training loss: 1.7364...  0.0539 sec/batch
Epoch: 1/20...  Training Step: 2535...  Training loss: 1.8833...  0.0637 sec/batch
Epoch: 1/20...  Training Step: 2536...  Training loss: 1.9119...  0.0452 sec/batch
Epoch: 1/20...  Training Step: 2537...  Training loss: 1.8229...  0.0453 sec/batch
Epoch: 1/20...  Training Step: 2538...  Training loss: 1.9520...  0.0544 sec/batch
Epoch: 1/20...  Training Step: 2539...  Training loss: 1.9307...  0.0565 sec/batch
Epoch: 1/20...  Training Step: 2540...  Training loss: 1.8736...  0.0459 sec/batch
Epoch: 1/20...  Training Step: 2541...  Training loss: 1.8351...  0.0456 sec/batch
Epoc

KeyboardInterrupt: 

#### Saved checkpoints

Read up on saving and loading checkpoints here: https://www.tensorflow.org/programmers_guide/variables

In [ ]:
tf.train.get_checkpoint_state('checkpoints')

## Sampling

Now that the network is trained, we'll can use it to generate new text. The idea is that we pass in a character, then the network will predict the next character. We can use the new one, to predict the next one. And we keep doing this to generate all new text. I also included some functionality to prime the network with some text by passing in a string and building up a state from that.

The network gives us predictions for each character. To reduce noise and make things a little less random, I'm going to only choose a new character from the top N most likely characters.



In [ ]:
def pick_top_n(preds, vocab_size, top_n=5):
    p = np.squeeze(preds)
    p[np.argsort(p)[:-top_n]] = 0
    p = p / np.sum(p)
    c = np.random.choice(vocab_size, 1, p=p)[0]
    return c

In [ ]:
def sample(checkpoint, n_samples, lstm_size, vocab_size, prime="The "):
    samples = [c for c in prime]
    model = CharRNN(len(vocab), lstm_size=lstm_size, sampling=True)
    saver = tf.train.Saver()
    with tf.Session() as sess:
        saver.restore(sess, checkpoint)
        new_state = sess.run(model.initial_state)
        for c in prime:
            x = np.zeros((1, 1))
            x[0,0] = vocab_to_int[c]
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

        c = pick_top_n(preds, len(vocab))
        samples.append(int_to_vocab[c])

        for i in range(n_samples):
            x[0,0] = c
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

            c = pick_top_n(preds, len(vocab))
            samples.append(int_to_vocab[c])
        
    return ''.join(samples)

Here, pass in the path to a checkpoint and sample from the network.

In [ ]:
tf.train.latest_checkpoint('checkpoints')

In [ ]:
checkpoint = tf.train.latest_checkpoint('checkpoints')
samp = sample(checkpoint, 2000, lstm_size, len(vocab), prime="Far")
print(samp)

In [ ]:
checkpoint = 'checkpoints/i200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

In [ ]:
checkpoint = 'checkpoints/i600_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

In [ ]:
checkpoint = 'checkpoints/i1200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)